# Generated by Django 4.1.13 on 2024-06-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_alter_task_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasktag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tasktag',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
