# Generated by Django 4.1.13 on 2024-06-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0005_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='diary_images')),
                ('tags', models.ManyToManyField(blank=True, to='todoApp.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.user')),
            ],
        ),
    ]
